"""Add Table Address

Revision ID: 72ae243345b1
Revises: b864ae840077
Create Date: 2022-09-07 16:16:17.760272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ae243345b1'
down_revision = 'b864ae840077'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
